const teams = {
  Bears: 'chi',
  Bengals: 'cin',
  Bills: 'buf',
  Broncos: 'den',
  Browns: 'cle',
  Buccaneers: 'tb',
  Cardinals: 'ari',
  Chargers: 'lac',
  Chiefs: 'kc',
  Colts: 'ind',
  Cowboys: 'dal',
  Dolphins: 'mia',
  Eagles: 'phi',
  Falcons: 'atl',
  Giants: 'nyg',
  Jaguars: 'jac',
  Jets: 'nyj',
  Lions: 'det',
  Packers: 'gb',
  Panthers: 'car',
  Patriots: 'ne',
  Raiders: 'oak',
  Rams: 'lar',
  Ravens: 'bal',
  Redskins: 'was',
  Saints: 'no',
  Seahawks: 'sea',
  Steelers: 'pit',
  Texans: 'hou',
  Titans: 'ten',
  Vikings: 'min',
  '49ers': 'sf',
}

export default teams
